/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import query.JDlgConsultaVendas;
import query.JDlgConsultasClientes;
import query.JDlgConsultasGuitarra;
import query.JDlgConsultasUsuarios;
import query.JDlgConsultasVendedor;

/**
 *
 * @author u07032685110
 */
public class JFrmPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal() {
        initComponents();
        setTitle("Compra e Venda de Guitarras");

setExtendedState(MAXIMIZED_BOTH);

    }

    JFrmPrincipal(Object object, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jBtnUsuario = new javax.swing.JButton();
        jBtnVendedor = new javax.swing.JButton();
        jBtnCliente = new javax.swing.JButton();
        jBtnVendas = new javax.swing.JButton();
        jBtnGuitarra = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMnuPrincipal = new javax.swing.JMenu();
        jMnuUsuarios = new javax.swing.JMenuItem();
        jMnuCliente = new javax.swing.JMenuItem();
        jMnuVendedor = new javax.swing.JMenuItem();
        jMnuGuitarra = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuSair = new javax.swing.JMenuItem();
        jMnuMovimento = new javax.swing.JMenu();
        jMnuVendas = new javax.swing.JMenuItem();
        jMenuVendasProduto = new javax.swing.JMenuItem();
        jMnuMovimento1 = new javax.swing.JMenu();
        jMnuConsultaVendas = new javax.swing.JMenu();
        jMnuUsuarioConsulta = new javax.swing.JMenuItem();
        jMnuGuitarraConsulta = new javax.swing.JMenuItem();
        jMnuClienteConsulta = new javax.swing.JMenuItem();
        jMnuConsultaVendedor = new javax.swing.JMenuItem();
        jMnuConsultaVenda = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().setLayout(null);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jBtnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 30));

        jBtnVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vendedor.png"))); // NOI18N
        jBtnVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVendedorActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 50, 30));

        jBtnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente_1.png"))); // NOI18N
        jBtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 50, 30));

        jBtnVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produto.png"))); // NOI18N
        jBtnVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVendasActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 50, 30));

        jBtnGuitarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guitarra.png"))); // NOI18N
        jBtnGuitarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuitarraActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnGuitarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 50, 30));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 50);

        jMnuPrincipal.setMnemonic('P');
        jMnuPrincipal.setText("Principal");

        jMnuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jMnuUsuarios.setMnemonic('U');
        jMnuUsuarios.setText("Usuario");
        jMnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuariosActionPerformed(evt);
            }
        });
        jMnuPrincipal.add(jMnuUsuarios);

        jMnuCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente_1.png"))); // NOI18N
        jMnuCliente.setText("Cliente");
        jMnuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClienteActionPerformed(evt);
            }
        });
        jMnuPrincipal.add(jMnuCliente);

        jMnuVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vendedor.png"))); // NOI18N
        jMnuVendedor.setText("Vendedor");
        jMnuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendedorActionPerformed(evt);
            }
        });
        jMnuPrincipal.add(jMnuVendedor);

        jMnuGuitarra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMnuGuitarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guitarra.png"))); // NOI18N
        jMnuGuitarra.setText("Guitarra");
        jMnuGuitarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuGuitarraActionPerformed(evt);
            }
        });
        jMnuPrincipal.add(jMnuGuitarra);
        jMnuPrincipal.add(jSeparator1);

        jMnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        jMnuSair.setText("Sair");
        jMnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSairActionPerformed(evt);
            }
        });
        jMnuPrincipal.add(jMnuSair);

        jMenuBar2.add(jMnuPrincipal);

        jMnuMovimento.setMnemonic('M');
        jMnuMovimento.setText("Movimento");

        jMnuVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produto.png"))); // NOI18N
        jMnuVendas.setText("Vendas");
        jMnuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendasActionPerformed(evt);
            }
        });
        jMnuMovimento.add(jMnuVendas);

        jMenuVendasProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuVendasProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produto.png"))); // NOI18N
        jMenuVendasProduto.setText("Vendas Produtos");
        jMnuMovimento.add(jMenuVendasProduto);

        jMnuMovimento1.setMnemonic('M');
        jMnuMovimento1.setText("Movimento");
        jMnuMovimento.add(jMnuMovimento1);

        jMenuBar2.add(jMnuMovimento);

        jMnuConsultaVendas.setMnemonic('M');
        jMnuConsultaVendas.setText("Consultas");

        jMnuUsuarioConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarioConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jMnuUsuarioConsulta.setText("Consulta Usuario");
        jMnuUsuarioConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuarioConsultaActionPerformed(evt);
            }
        });
        jMnuConsultaVendas.add(jMnuUsuarioConsulta);

        jMnuGuitarraConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuGuitarraConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guitarra.png"))); // NOI18N
        jMnuGuitarraConsulta.setText("Consulta Guitarra");
        jMnuGuitarraConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuGuitarraConsultaActionPerformed(evt);
            }
        });
        jMnuConsultaVendas.add(jMnuGuitarraConsulta);

        jMnuClienteConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuClienteConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMnuClienteConsulta.setText("Consulta Clientes");
        jMnuClienteConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClienteConsultaActionPerformed(evt);
            }
        });
        jMnuConsultaVendas.add(jMnuClienteConsulta);

        jMnuConsultaVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultaVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vendedor.png"))); // NOI18N
        jMnuConsultaVendedor.setText("Consulta Vendedor");
        jMnuConsultaVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultaVendedorActionPerformed(evt);
            }
        });
        jMnuConsultaVendas.add(jMnuConsultaVendedor);

        jMnuConsultaVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produto.png"))); // NOI18N
        jMnuConsultaVenda.setText("Consulta Vendas");
        jMnuConsultaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultaVendaActionPerformed(evt);
            }
        });
        jMnuConsultaVendas.add(jMnuConsultaVenda);

        jMenuBar2.add(jMnuConsultaVendas);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClienteActionPerformed
      JDlgClientes Cliente = new JDlgClientes(null, true);
       Cliente.setVisible(true);  
    }//GEN-LAST:event_jMnuClienteActionPerformed

    private void jMnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuariosActionPerformed
    JDlgUsuarios Usuario = new JDlgUsuarios(null, true);
    Usuario.setVisible(true);
    }//GEN-LAST:event_jMnuUsuariosActionPerformed

    private void jMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSairActionPerformed
    System.exit(0);        
    }//GEN-LAST:event_jMnuSairActionPerformed

    private void jMnuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendedorActionPerformed
       JDlgVendedor Vendedor = new JDlgVendedor(null, true);
    Vendedor.setVisible(true);
    }//GEN-LAST:event_jMnuVendedorActionPerformed

    private void jMnuGuitarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuGuitarraActionPerformed
    JDlgGuitarra Guitarra = new JDlgGuitarra(null, true);
    Guitarra.setVisible(true);
    }//GEN-LAST:event_jMnuGuitarraActionPerformed

    private void jMnuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendasActionPerformed

    }//GEN-LAST:event_jMnuVendasActionPerformed

    private void jMnuUsuarioConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuarioConsultaActionPerformed
   JDlgConsultasUsuarios consultaUsuario = new JDlgConsultasUsuarios(null,true);
   consultaUsuario.setVisible(true);
    }//GEN-LAST:event_jMnuUsuarioConsultaActionPerformed

    private void jMnuGuitarraConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuGuitarraConsultaActionPerformed
   JDlgConsultasGuitarra consultaGuitarra = new JDlgConsultasGuitarra(null,true);
   consultaGuitarra.setVisible(true);
    }//GEN-LAST:event_jMnuGuitarraConsultaActionPerformed

    private void jMnuClienteConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClienteConsultaActionPerformed
   JDlgConsultasClientes consultaClientes = new JDlgConsultasClientes(null,true);
   consultaClientes.setVisible(true);
    }//GEN-LAST:event_jMnuClienteConsultaActionPerformed

    private void jMnuConsultaVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultaVendedorActionPerformed
   JDlgConsultasVendedor consultaVendedor = new JDlgConsultasVendedor(null,true);
   consultaVendedor.setVisible(true);
    }//GEN-LAST:event_jMnuConsultaVendedorActionPerformed

    private void jMnuConsultaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultaVendaActionPerformed
   JDlgConsultaVendas consultaVendas = new JDlgConsultaVendas(null,true);
   consultaVendas.setVisible(true);
    }//GEN-LAST:event_jMnuConsultaVendaActionPerformed

    private void jBtnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUsuarioActionPerformed
    JDlgConsultasUsuarios Usuario = new JDlgConsultasUsuarios(null, true);
    Usuario.setVisible(true);
    }//GEN-LAST:event_jBtnUsuarioActionPerformed

    private void jBtnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVendasActionPerformed
   JDlgConsultaVendas consultaVendas = new JDlgConsultaVendas(null,true);
   consultaVendas.setVisible(true);
    }//GEN-LAST:event_jBtnVendasActionPerformed

    private void jBtnGuitarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuitarraActionPerformed
   JDlgConsultasGuitarra consultaGuitarra = new JDlgConsultasGuitarra(null,true);
   consultaGuitarra.setVisible(true);
    }//GEN-LAST:event_jBtnGuitarraActionPerformed

    private void jBtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClienteActionPerformed
   JDlgConsultasClientes consultaClientes = new JDlgConsultasClientes(null,true);
   consultaClientes.setVisible(true);
    }//GEN-LAST:event_jBtnClienteActionPerformed

    private void jBtnVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVendedorActionPerformed
   JDlgConsultasVendedor consultaVendedor = new JDlgConsultasVendedor(null,true);
   consultaVendedor.setVisible(true);
    }//GEN-LAST:event_jBtnVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCliente;
    private javax.swing.JButton jBtnGuitarra;
    private javax.swing.JButton jBtnUsuario;
    private javax.swing.JButton jBtnVendas;
    private javax.swing.JButton jBtnVendedor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuVendasProduto;
    private javax.swing.JMenuItem jMnuCliente;
    private javax.swing.JMenuItem jMnuClienteConsulta;
    private javax.swing.JMenuItem jMnuConsultaVenda;
    private javax.swing.JMenu jMnuConsultaVendas;
    private javax.swing.JMenuItem jMnuConsultaVendedor;
    private javax.swing.JMenuItem jMnuGuitarra;
    private javax.swing.JMenuItem jMnuGuitarraConsulta;
    private javax.swing.JMenu jMnuMovimento;
    private javax.swing.JMenu jMnuMovimento1;
    private javax.swing.JMenu jMnuPrincipal;
    private javax.swing.JMenuItem jMnuSair;
    private javax.swing.JMenuItem jMnuUsuarioConsulta;
    private javax.swing.JMenuItem jMnuUsuarios;
    private javax.swing.JMenuItem jMnuVendas;
    private javax.swing.JMenuItem jMnuVendedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
