package bean;
// Generated 16/09/2023 15:19:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GuitarraCwmo generated by hbm2java
 */
@Entity
@Table(name="guitarra_cwmo"
    ,catalog="test"
//   , catalog="db_carlos_oliveira"     
)
public class GuitarraCwmo  implements java.io.Serializable {


     private int idprodutosCwmo;
     private String tipoCwmo;
     private String trastesCwmo;
     private String modeloCwmo;
     private String captadoresCwmo;
     private String ponteCwmo;
     private int canhotoDestroCwmo;
     private Double valorUnitarioCwmo;


    public GuitarraCwmo() {
    }

	
    public GuitarraCwmo(int idprodutosCwmo, String tipoCwmo, String trastesCwmo, String modeloCwmo, String captadoresCwmo, String ponteCwmo, int canhotoDestroCwmo, Double valorUnitarioCwmo) {
        this.idprodutosCwmo = idprodutosCwmo;
        this.tipoCwmo = tipoCwmo;
        this.trastesCwmo = trastesCwmo;
        this.modeloCwmo = modeloCwmo;
        this.captadoresCwmo = captadoresCwmo;
        this.ponteCwmo = ponteCwmo;
        this.canhotoDestroCwmo = canhotoDestroCwmo;
        this.valorUnitarioCwmo = valorUnitarioCwmo;
    }
    public GuitarraCwmo(int idprodutosCwmo, String tipoCwmo, String trastesCwmo, String modeloCwmo, String captadoresCwmo, String ponteCwmo, int canhotoDestroCwmo, Set vendasProdutoCwmos, Double valorUnitarioCwmo) {
       this.idprodutosCwmo = idprodutosCwmo;
       this.tipoCwmo = tipoCwmo;
       this.trastesCwmo = trastesCwmo;
       this.modeloCwmo = modeloCwmo;
       this.captadoresCwmo = captadoresCwmo;
       this.ponteCwmo = ponteCwmo;
       this.canhotoDestroCwmo = canhotoDestroCwmo;
       this.valorUnitarioCwmo = valorUnitarioCwmo;
    }
   
     @Id 

    
    @Column(name="idprodutos_cwmo", unique=true, nullable=false)
    public int getIdprodutosCwmo() {
        return this.idprodutosCwmo;
    }
    
    public void setIdprodutosCwmo(int idprodutosCwmo) {
        this.idprodutosCwmo = idprodutosCwmo;
    }

    
    @Column(name="tipo_cwmo", nullable=false, length=10)
    public String getTipoCwmo() {
        return this.tipoCwmo;
    }
    
    public void setTipoCwmo(String tipoCwmo) {
        this.tipoCwmo = tipoCwmo;
    }

    
    @Column(name="trastes_cwmo", nullable=false, length=2)
    public String getTrastesCwmo() {
        return this.trastesCwmo;
    }
    
    public void setTrastesCwmo(String trastesCwmo) {
        this.trastesCwmo = trastesCwmo;
    }

    
    @Column(name="modelo_cwmo", nullable=false, length=40)
    public String getModeloCwmo() {
        return this.modeloCwmo;
    }
    
    public void setModeloCwmo(String modeloCwmo) {
        this.modeloCwmo = modeloCwmo;
    }

    
    @Column(name="captadores_cwmo", nullable=false, length=15)
    public String getCaptadoresCwmo() {
        return this.captadoresCwmo;
    }
    
    public void setCaptadoresCwmo(String captadoresCwmo) {
        this.captadoresCwmo = captadoresCwmo;
    }

    
    @Column(name="ponte_cwmo", nullable=false, length=15)
    public String getPonteCwmo() {
        return this.ponteCwmo;
    }
    
    public void setPonteCwmo(String ponteCwmo) {
        this.ponteCwmo = ponteCwmo;
    }

    
    @Column(name="canhotoDestro_cwmo", nullable=false, length=10)
    public int getCanhotoDestroCwmo() {
        return this.canhotoDestroCwmo;
    }
    
    public void setCanhotoDestroCwmo(int canhotoDestroCwmo) {
        this.canhotoDestroCwmo = canhotoDestroCwmo;
    }

    @Column(name="valorUnitario_Cwmo", nullable=false, precision=5)
    public Double getValorUnitarioCwmo() {
        return this.valorUnitarioCwmo;
    }
    
    public void setValorUnitarioCwmo(Double valorUnitarioCwmo) {
        this.valorUnitarioCwmo = valorUnitarioCwmo;
    }

     public String toString() {
    return modeloCwmo;
}
     @Override
      public boolean equals (Object object){
      if(object instanceof GuitarraCwmo){
      GuitarraCwmo guitarraCwmo = (GuitarraCwmo) object;
        if(this.getIdprodutosCwmo()== guitarraCwmo.getIdprodutosCwmo())
            return true;
                }         
                return false;
            }
         
}


