package bean;
// Generated 16/09/2023 15:19:00 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendasCwmo generated by hbm2java
 */
@Entity
@Table(name="vendas_cwmo"
    ,catalog="test"
//   , catalog="db_carlos_oliveira"      
)
public class VendasCwmo  implements java.io.Serializable {


     private int idvendasCwmo;
     private ClientesCwmo clientesCwmo;
     private VendedorCwmo vendedorCwmo;
     private Date dataCwmo;
     private double totalCwmo;

    public VendasCwmo() {
    }

	
    public VendasCwmo(int idvendasCwmo, ClientesCwmo clientesCwmo, VendedorCwmo vendedorCwmo, Date dataCwmo, double totalCwmo) {
        this.idvendasCwmo = idvendasCwmo;
        this.clientesCwmo = clientesCwmo;
        this.vendedorCwmo = vendedorCwmo;
        this.dataCwmo = dataCwmo;
        this.totalCwmo = totalCwmo;
    }
    public VendasCwmo(int idvendasCwmo, ClientesCwmo clientesCwmo, VendedorCwmo vendedorCwmo, Date dataCwmo, double totalCwmo, Set vendasProdutoCwmos) {
       this.idvendasCwmo = idvendasCwmo;
       this.clientesCwmo = clientesCwmo;
       this.vendedorCwmo = vendedorCwmo;
       this.dataCwmo = dataCwmo;
       this.totalCwmo = totalCwmo;
    }
   
     @Id 

    
    @Column(name="idvendas_cwmo", unique=true, nullable=false)
    public int getIdvendasCwmo() {
        return this.idvendasCwmo;
    }
    
    public void setIdvendasCwmo(int idvendasCwmo) {
        this.idvendasCwmo = idvendasCwmo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkcliente_cwmo", nullable=false)
    public ClientesCwmo getClientesCwmo() {
        return this.clientesCwmo;
    }
    
    public void setClientesCwmo(ClientesCwmo clientesCwmo) {
        this.clientesCwmo = clientesCwmo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkvendedor_cwmo", nullable=false)
    public VendedorCwmo getVendedorCwmo() {
        return this.vendedorCwmo;
    }
    
    public void setVendedorCwmo(VendedorCwmo vendedorCwmo) {
        this.vendedorCwmo = vendedorCwmo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_cwmo", nullable=false, length=10)
    public Date getDataCwmo() {
        return this.dataCwmo;
    }
    
    public void setDataCwmo(Date dataCwmo) {
        this.dataCwmo = dataCwmo;
    }

    
    @Column(name="total_cwmo", nullable=false, precision=5)
    public double getTotalCwmo() {
        return this.totalCwmo;
    }
    
    public void setTotalCwmo(double totalCwmo) {
        this.totalCwmo = totalCwmo;
    }



}


